import{S as p,i as a}from"./assets/vendor-5ObWk2rO.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const m="46892237-a54e01ec2b73ea1c4de56cebe",y="https://pixabay.com/api/";function h(s,t=1,n=20){const r=`${y}?key=${m}&q=${encodeURIComponent(s)}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${n}`;return fetch(r).then(e=>{if(!e.ok)throw new Error("Network response was not ok");return e.json()}).then(e=>e.hits).catch(e=>{throw console.error("Error fetching images:",e),e})}let c;function g(s,t){t.innerHTML="";const n=s.map(r=>`
      <a href="${r.largeImageURL}" class="gallery-item">
        <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy"/>
        <div class="image-info">
          <p><b>Likes:</b> ${r.likes}</p>
          <p><b>Views:</b> ${r.views}</p>
          <p><b>Comments:</b> ${r.comments}</p>
          <p><b>Downloads:</b> ${r.downloads}</p>
        </div>
      </a>`).join("");t.insertAdjacentHTML("beforeend",n),c?c.refresh():c=new p(".gallery-item",{captionsData:"alt",captionDelay:250})}const b=document.querySelector("#search-form"),u=document.querySelector(".gallery"),l=document.querySelector(".loader");let f="",d=1;b.addEventListener("submit",s=>{s.preventDefault();const t=s.currentTarget.elements.query.value.trim();if(!t){a.error({title:"Error",message:"Please enter a search term"});return}u.innerHTML="",f=t,d=1,l.style.display="block",h(f,d).then(n=>{if(l.style.display="none",n.length===0){a.info({message:"Sorry, there are no images matching your search query. Please try again!"});return}g(n,u)}).catch(n=>{l.style.display="none",a.error({title:"Error",message:n.message})})});
//# sourceMappingURL=index.js.map
